import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{parseContainer,SubsetModel,decodeTGA}from'../src/shared/inochi-runtime.mjs';
const p=parseContainer(readFileSync(new URL('./fixtures/inochi-smoke.inp',import.meta.url)));const clone=()=>structuredClone(p.model),make=m=>new SubsetModel(m,p.textures.length);
const oracle=JSON.parse(readFileSync(new URL('./fixtures/inochi-smoke-oracle.json',import.meta.url)));
for(const c of oracle.cases)test(`Creator exported numeric oracle ${c.ParamBreath}`,()=>{const f=make(clone()).frame({ParamBreath:c.ParamBreath});c.expected_world_vertices.forEach(([x,y],i)=>{assert.ok(Math.abs(f.vertices[i*4]-x)<.00002);assert.ok(Math.abs(f.vertices[i*4+1]-y)<.00002)})});
test('real exported TGA decode',()=>{const t=decodeTGA(p.textures[0].bytes);assert.equal(t.width,2048);assert.equal(t.height,2048);assert.ok(t.pixels.some((v,i)=>i%4===3&&v>0))});
for(const[key,edit]of Object.entries({mask:m=>m.nodes.children[0].masks=[1],composite:m=>m.nodes.type='Composite',blend:m=>m.nodes.children[0].blend_mode='Multiply',physicsNode:m=>m.nodes.children[0].type='SimplePhysics',vector:m=>m.param[0].is_vec2=true,nonlinear:m=>m.param[0].bindings[0].interpolate_mode='Cubic',unknownBinding:m=>m.param[0].bindings[0].param_name='mystery',rotationX:m=>m.nodes.transform.rot[0]=1,badIndex:m=>m.nodes.children[0].mesh.indices[0]=999,badNumber:m=>m.param[0].bindings[0].values[0][0]=NaN,automation:m=>m.automation={name:'ignored?'},tint:m=>m.nodes.children[0].tint=[.5,1,1],textureAux:m=>m.nodes.children[0].textures[1]=0}))test('reject '+key,()=>{const m=clone();edit(m);assert.throws(()=>make(m),/Unsupported\/invalid/)});
test('reject truncated and wrong-format files',()=>{assert.throws(()=>parseContainer(new Uint8Array(20)));assert.throws(()=>parseContainer(readFileSync(new URL('./fixtures/inochi-smoke.inp',import.meta.url)).slice(0,100)))});
test('reject nonfinite control',()=>assert.throws(()=>make(clone()).frame({ParamBreath:NaN})));
test('all eight base motion roles change final-model vertices',()=>{const d=parseContainer(readFileSync(new URL('../assets/inochi/WhaleGirl.inp',import.meta.url)));const roles=new Set(['ParamBreath','ParamAngleX','ParamAngleY','ParamAngleZ','ParamBodyAngleX','ParamBodyAngleY','ParamBounce','ParamHairSway']);d.model.param=d.model.param.filter(p=>roles.has(p.name));const m=new SubsetModel(d.model,d.textures.length);assert.equal(m.params.length,8);for(const p of m.params){const a=m.frame({[p.name]:p.min[0]}),b=m.frame({[p.name]:p.max[0]});assert.ok(a.vertices.some((x,i)=>i%4<2&&Math.abs(x-b.vertices[i])>.00001),p.name)}});
test('unkeyed extrapolation rejected explicitly',()=>assert.throws(()=>make(clone()).frame({ParamBreath:-1}),/unkeyed/));
test('software rasterizer produces actual changed textured pixels',async()=>{const{SoftwareMeshRenderer}=await import('../src/renderer/inochi/software-renderer.mjs');globalThis.ImageData=class{constructor(data,width,height){Object.assign(this,{data,width,height})}};let image;const canvas={width:640,height:480,getContext:()=>({putImageData:v=>image=v,getImageData:()=>image})};const t=decodeTGA(p.textures[0].bytes);for(let i=0;i<t.pixels.length;i+=4)for(let j=0;j<3;j++)t.pixels[i+j]=Math.round(t.pixels[i+j]*t.pixels[i+3]/255);const r=new SoftwareMeshRenderer(canvas,{texture:()=>t}),m=make(clone());r.draw(m.frame({ParamBreath:0}));const a=r.readPixels().slice();r.draw(m.frame({ParamBreath:1}));const b=r.readPixels();let changed=0;for(let i=0;i<a.length;i+=4)if(a.subarray(i,i+4).some((v,j)=>v!==b[i+j]))changed++;assert.ok(changed>100,changed);console.log('Software changed pixels:',changed)});
test('index budget and safe expansion',()=>{const m=clone();m.nodes.children[0].mesh.indices=Array.from({length:150000},(_,i)=>i%3);const f=make(m).frame();assert.equal(f.indices.length,150000);m.nodes.children[0].mesh.indices=Array.from({length:300003},(_,i)=>i%3);assert.throws(()=>make(m),/index limit/)});
async function tinyRaster(frame,texture={width:1,height:1,pixels:new Uint8Array([128,0,0,128])}){const{SoftwareMeshRenderer}=await import('../src/renderer/inochi/software-renderer.mjs');globalThis.ImageData=class{constructor(data,width,height){Object.assign(this,{data,width,height})}};let image;const canvas={width:16,height:16,getContext:()=>({putImageData:v=>image=v,getImageData:()=>image})};const r=new SoftwareMeshRenderer(canvas,{texture:()=>texture});r.draw(frame);return{r,pixels:()=>image.data}}
const triangleFrame=(indices)=>({vertices:new Float32Array([-1,-1,0,0,1,-1,1,0,-1,1,0,1]),indices:new Uint32Array(indices),commands:[{state:0,blend:0,type:0x101,texture:0,indexOffset:0,count:indices.length,opacity:1}]});
test('genuine overlapping translucent triangles source-over twice',async()=>{const{pixels}=await tinyRaster(triangleFrame([0,1,2,0,1,2]));const alpha=Array.from(pixels()).filter((_v,i)=>i%4===3);assert.equal(Math.max(...alpha),192)});
test('shared-edge adjacent triangles do not double paint seam',async()=>{const f={...triangleFrame([0,1,2,2,1,3]),vertices:new Float32Array([-1,-1,0,0,1,-1,1,0,-1,1,0,1,1,1,1,1])};const{pixels}=await tinyRaster(f);assert.equal(Math.max(...Array.from(pixels()).filter((_v,i)=>i%4===3)),128)});
test('excessively overlapping CPU raster work fails boundedly',async()=>{await assert.rejects(()=>tinyRaster(triangleFrame(Array.from({length:3000},(_,i)=>i%3))),/raster-work budget/)});
for(const[key,edit]of Object.entries({legacyMask:m=>m.nodes.children[0].masked_by=[1],negativeTexture:m=>m.nodes.children[0].textures[0]=-1,fractionalTexture:m=>m.nodes.children[0].textures[0]=.5,outsideUV:m=>m.nodes.children[0].mesh.uvs[0]=-2}))test('reject '+key,()=>{const m=clone();edit(m);assert.throws(()=>make(m),/Unsupported\/invalid/)});
test('finite doubles overflowing Float32 positions reject explicitly',()=>{const m=clone();m.nodes.transform.trans[0]=1e100;assert.throws(()=>make(m).frame(),/Float32/)});
