import layout from '../../assets/keyboard.layout.json';
import rig from '../../assets/inochi/input-rig.json';
import {PhysicalInput}from './physical-input';
import {physicalPose}from '../renderer/inochi/physical-pose';
import type{SubsetModel,InochiFrame}from './inochi-runtime.mjs';
/** Actual mesh displacement moves the authored fingertip to its key, not just parameter equality. */
export function validatePhysicalRig(model:SubsetModel){if(layout.keys.length!==83)throw Error('Physical keyboard must contain all83 supported keys');
 const input=new PhysicalInput(layout.keys,()=>100),base=model.frame(physicalPose(undefined,true));
 const ids=new Map([...model.nodes].map(([id,{n}])=>[n.name,id]));
 const points=(frame:InochiFrame,name:string)=>{const command=frame.commands.find(c=>c.partId===ids.get(name));if(!command)throw Error('Missing physical part '+name);const indices=new Set(frame.indices.slice(command.indexOffset,command.indexOffset+command.count));return [...indices].map(i=>[frame.vertices[i*4],frame.vertices[i*4+1]])};
 const anchors=new Map<string,{indices:number[];weights:number[]}>();
 for(const h of [rig.hands.L,rig.hands.R,rig.hands.mouse]){const ref='finger_anchor'in h?h.finger_anchor:h.reference_anchor;const id=ids.get(h.hand_layer),n=model.nodes.get(id!)!.n,m=n.mesh;const px=ref[0]-627,py=ref[1]-627;let found=false;for(let j=0;j<m.indices.length;j+=3){const ix=m.indices.slice(j,j+3),v=ix.map((i:number)=>[m.verts[i*2]-m.origin[0],m.verts[i*2+1]-m.origin[1]]),[a,b,c]=v,den=(b[1]-c[1])*(a[0]-c[0])+(c[0]-b[0])*(a[1]-c[1]);if(Math.abs(den)<1e-9)continue;const w0=((b[1]-c[1])*(px-c[0])+(c[0]-b[0])*(py-c[1]))/den,w1=((c[1]-a[1])*(px-c[0])+(a[0]-c[0])*(py-c[1]))/den,w2=1-w0-w1;if(Math.min(w0,w1,w2)>=-1e-5){anchors.set(h.hand_layer,{indices:ix,weights:[w0,w1,w2]});found=true;break}}if(!found)throw Error('Authored fingertip/reference outside rigid hand mesh: '+h.hand_layer);}
 const absolute=(f:InochiFrame,name:string,x:number,y:number)=>{const id=ids.get(name)!,n=model.nodes.get(id)!.n,cmd=f.commands.find(c=>c.partId===id)!,offset=f.indices[cmd.indexOffset]-n.mesh.indices[0],a=anchors.get(name)!;let wx=0,wy=0;for(let k=0;k<3;k++){wx+=f.vertices[(offset+a.indices[k])*4]*a.weights[k];wy+=f.vertices[(offset+a.indices[k])*4+1]*a.weights[k]}const error=Math.max(Math.abs(wx-(x-627)),Math.abs(wy-(y-627)));if(error>.02)throw Error(name+' absolute fingertip/reference mismatch: '+error);return error;};
 absolute(base,rig.hands.L.hand_layer,...rig.hands.L.finger_anchor as [number,number]);absolute(base,rig.hands.R.hand_layer,...rig.hands.R.finger_anchor as [number,number]);absolute(base,rig.hands.mouse.hand_layer,...rig.hands.mouse.reference_anchor as [number,number]);
 const check=(f:InochiFrame,name:string,dx:number,dy:number)=>{const a=points(base,name),b=points(f,name);if(a.length!==b.length)throw Error('Unstable topology');let worst=0;for(let i=0;i<a.length;i++)worst=Math.max(worst,Math.abs(b[i][0]-a[i][0]-dx),Math.abs(b[i][1]-a[i][1]-dy));if(worst>.02)throw Error(name+' fingertip displacement mismatch: '+worst);return worst};let maximumError=0;
 for(const k of layout.keys){input.reset();input.keyDown(k.nativeCode);const side=k.hand==='left'?'L':'R',h=rig.hands[side],values=physicalPose(input.snapshot(),true),f=model.frame(values);maximumError=Math.max(maximumError,absolute(f,h.hand_layer,k.x,k.y+h.press_pixels),check(f,h.hand_layer,k.x-h.finger_anchor[0],k.y-h.finger_anchor[1]+h.press_pixels));input.keyUp(k.nativeCode);const released=model.frame(physicalPose(input.snapshot(),true));maximumError=Math.max(maximumError,check(released,h.hand_layer,0,0));}
 for(const x of [-1,0,1])for(const y of [-1,0,1]){input.reset();input.move(x,y);const values=physicalPose(input.snapshot(),true),f=model.frame(values);maximumError=Math.max(maximumError,absolute(f,rig.hands.mouse.hand_layer,values.ParamMouseX,values.ParamMouseY),check(f,rig.hands.mouse.hand_layer,values.ParamMouseX-rig.hands.mouse.reference_anchor[0],values.ParamMouseY-rig.hands.mouse.reference_anchor[1]));}
 return {keys:layout.keys.length,mousePositions:9,maximumFingertipErrorSourcePixels:maximumError,source:'Actual transformed vertices, authored anchors and press depth'};
}
