import keyboardLayout from '../../assets/keyboard.layout.json';
import {physicalDemo} from '../shared/physical-demo';
import type { PhysicalInputSnapshot } from '../shared/physical-input';
import { MealPreview } from '../shared/preview-meal';
import { AnimationFrameLoop } from '../shared/animation-frame-loop';
import type { AppSettings } from '../main/config';
import { isWithinSleepSchedule } from '../shared/domain';
import { Character2D } from './character2d';
import { InochiRenderer } from './inochi';
import { AudioController,type AudioState } from './audio';
window.__errors=[];window.addEventListener('error',event=>window.__errors!.push(event.message));window.addEventListener('unhandledrejection',event=>window.__errors!.push(String(event.reason)));
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
// Keep current input while bootstrap/model loads; never replay an older held-key snapshot.
let physical:PhysicalInputSnapshot|undefined,physicalReceived=false,physicalPreviewStarted=-Infinity;
window.whale.on('physical-input',snapshot=>{physicalReceived=true;physical=snapshot;physicalPreviewStarted=-Infinity;$('physical-keys').textContent=snapshot.pressed.length?'当前物理键：'+snapshot.pressed.map((id:string)=>keyboardLayout.keys.find(k=>k.id===id)?.labelMac||id).join(' + '):'当前没有按住的物理键';});
window.whale.on('physical-preview',()=>{physicalPreviewStarted=performance.now();});
// Subscribe before either async load so a hide/minimize during startup is retained.
const previewLoop=new AnimationFrameLoop({onFrame:()=>animate()});
previewLoop.setBlocked('model-loading',true);
const syncDocumentVisibility=()=>previewLoop.setBlocked('document-hidden',document.hidden);
syncDocumentVisibility();document.addEventListener('visibilitychange',syncDocumentVisibility);
let panelVisibilityRevision=0;
const stopPanelVisibility=window.whale.on('panel-visibility',visible=>{panelVisibilityRevision++;previewLoop.setBlocked('panel-hidden',!visible);});
previewLoop.resume();
window.addEventListener('beforeunload',()=>{previewLoop.destroy();stopPanelVisibility();document.removeEventListener('visibilitychange',syncDocumentVisibility);});
const bootstrapVisibilityRevision=panelVisibilityRevision;
const boot=await window.whale.bootstrap();
if(!physicalReceived)physical=boot.physical;
if(boot.ciSmoke)window.__setPhysicalQA=snapshot=>{physical=snapshot;physicalPreviewStarted=-Infinity;};
// An event received while bootstrap was in flight is newer than its snapshot.
if(panelVisibilityRevision===bootstrapVisibilityRevision)previewLoop.setBlocked('panel-hidden',!boot.panelVisible);
let settings=boot.settings;let previewGaze={x:0,y:0};let previewTyping=0,previewBounce=0,lastFrame=performance.now();let toastTimer:ReturnType<typeof setTimeout>;
function toast(message:string){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,7000);}
async function patch(value:Partial<AppSettings>){try{settings=await window.whale.updateSettings(value);paint();}catch(error){toast(String(error));}}
const mealPreview=new MealPreview();
const toggles=['randomMood','positionLocked','globalInputEnabled','sleepEnabled','alwaysOnTop','clickThrough','reducedMotion'] as const;const numbers=['scale','opacity','idleDelaySeconds','mealCooldownSeconds'] as const;
for(const id of toggles)$(id).addEventListener('change',()=>patch({[id]:$<HTMLInputElement>(id).checked}));for(const id of numbers)$(id).addEventListener('change',()=>patch({[id]:Number($<HTMLInputElement>(id).value)}));for(const id of ['sleepStart','sleepEnd'] as const)$(id).addEventListener('change',()=>patch({[id]:$<HTMLInputElement>(id).value}));
for(const button of document.querySelectorAll<HTMLButtonElement>('[data-mood]'))button.addEventListener('click',()=>patch({mood:button.dataset.mood as AppSettings['mood'],randomMood:false}));
function paint(){for(const id of toggles)$<HTMLInputElement>(id).checked=settings[id];for(const id of numbers)$<HTMLInputElement>(id).value=String(settings[id]);for(const id of ['sleepStart','sleepEnd'] as const)$<HTMLInputElement>(id).value=settings[id];$<HTMLSelectElement>('audioSource').value=settings.audioSource;$<HTMLSelectElement>('audioDeviceId').value=settings.audioDeviceId;$('device-label').hidden=settings.audioSource!=='microphone';$('refresh-devices').hidden=settings.audioSource!=='microphone';for(const b of document.querySelectorAll<HTMLButtonElement>('[data-mood]')){b.classList.toggle('active',!settings.randomMood&&b.dataset.mood===settings.mood);b.setAttribute('aria-pressed',String(!settings.randomMood&&b.dataset.mood===settings.mood));}$('scale-value').textContent=`${Math.round(settings.scale*100)}%`;$('opacity-value').textContent=`${Math.round(settings.opacity*100)}%`;$('sleep-status').textContent=settings.sleepEnabled?(isWithinSleepSchedule(settings,new Date())?'正在定时睡眠，关闭作息即可唤醒':'现在是清醒时段'):'作息已关闭，不会按时间强制睡觉';}
window.whale.on('settings',next=>{settings=next;paint();});function paintInput(status:any){$('input-status').textContent=status.message+` 本次系统键盘 ${status.counts?.typing??0} / 鼠标移动 ${status.counts?.pointer??0} / 系统点击 ${status.counts?.click??0}`;$('input-status').classList.toggle('error',!status.keyboard&&settings.globalInputEnabled);$('input-permission').hidden=boot.platform!=='darwin'||status.keyboard;}window.whale.on('input-status',paintInput);window.whale.on('notice',notice=>toast(notice.message));paintInput(boot.inputStatus);$('input-permission').addEventListener('click',async()=>{if(!settings.globalInputEnabled){toast('请先开启全局键鼠互动');return;}const result=await window.whale.requestInputPermission();toast(result.trusted?'系统辅助功能已允许，正在重新连接键鼠':'请在系统设置中允许当前 Whale Companion Inochi；如开启后仍无事件，请完全退出再打开应用');});$('input-retry').addEventListener('click',()=>{if(settings.globalInputEnabled)void patch({globalInputEnabled:true});else toast('请先开启全局键鼠互动');});
$('restore-button').addEventListener('click',()=>window.whale.restorePet());$('quit-button').addEventListener('click',()=>window.whale.quit());$('test-typing').addEventListener('click',()=>{previewTyping=performance.now()+800;window.whale.testInput('typing');});$('test-click').addEventListener('click',()=>{previewBounce=performance.now()+700;window.whale.testInput('click');});$('test-eating').addEventListener('click',()=>{mealPreview.start(performance.now());});
let audioState:AudioState={state:'off',message:'已关闭'};let audioLevel=0;const audio=new AudioController({onState:state=>{audioState=state;$('audio-toggle').textContent=state.state==='active'?'关闭律动':state.state==='requesting'?'取消开启':'开启律动';$('audio-status').textContent=state.message;$('audio-status').classList.toggle('error',state.state==='error');if(state.state==='active')void patch({audioEnabled:true});if(state.state==='off'||state.state==='error'){void patch({audioEnabled:false});audioLevel=0;$('audio-meter').style.width='0%';}},onLevel:level=>{audioLevel=level;$('audio-meter').style.width=`${Math.round(level*100)}%`;window.whale.audioLevel(level);}});
$('audio-toggle').addEventListener('click',()=>{if(audioState.state==='active'||audioState.state==='requesting'){void audio.stop();return;}if(isWithinSleepSchedule(settings,new Date())){toast('现在是作息睡眠时段，关闭作息或起床后再开启律动');return;}const source=settings.audioSource==='system'?{kind:'system' as const}:{kind:'microphone' as const,deviceId:settings.audioDeviceId||undefined};void audio.start(source);});
$('audioSource').addEventListener('change',async()=>{const source=$<HTMLSelectElement>('audioSource').value as AppSettings['audioSource'];void audio.stop();void patch({audioSource:source});});$('audioDeviceId').addEventListener('change',async()=>{const deviceId=$<HTMLSelectElement>('audioDeviceId').value;void audio.stop();void patch({audioDeviceId:deviceId});});async function refreshDevices(){try{const inputs=await audio.listInputs();const select=$<HTMLSelectElement>('audioDeviceId');select.replaceChildren(new Option('系统默认输入',''),...inputs.map(d=>new Option(d.label,d.deviceId)));select.value=settings.audioDeviceId;$('audio-status').textContent=inputs.length?'设备已刷新；未授权时设备名称可能隐藏':'没有可列出的音频输入设备';}catch(error){toast(String(error));}}$('refresh-devices').addEventListener('click',refreshDevices);
window.whale.on('model-status',status=>{$('model-status').textContent=[status.message,...status.warnings].join('；');$('model-status').classList.toggle('error',status.state==='error');});$('version').textContent=`鲸伴 ${boot.edition==='inochi'?'Inochi':'Cubism Dev'} ${boot.version} · ${boot.platform} · 全部本地运行`;$('live2d-section').hidden=boot.edition==='2d';if(boot.edition!=='2d'){$('edition-badge').textContent=boot.model.rendererType==='inochi-0.8-subset'?'Inochi · 真实网格模型':'普通2D预览 · 可选 Cubism 接入';$('model-status').textContent=boot.renderStatus?[boot.renderStatus.message,...boot.renderStatus.warnings].join('；'):boot.model.name?`已选择模型：${boot.model.name}`:'尚无已导入的匹配网格模型';}
for(const [id,fn] of [['choose-core',()=>window.whale.chooseCore()],['choose-model',()=>window.whale.chooseModel()]] as const)$(id).addEventListener('click',async()=>{try{const model=await fn();$('model-status').textContent=`${model.rendererType==='inochi-0.8-subset'?'Inochi 0.8':'Cubism'}：${model.name??'缺少模型'}`;}catch(error){toast(String(error));}});
window.whale.on('activity',event=>{mealPreview.activity(performance.now());if(event.kind==='typing')previewTyping=performance.now()+600;if(event.kind==='click')previewBounce=performance.now()+500;if(event.gaze)previewGaze=event.gaze;});const canvas=$<HTMLCanvasElement>('preview');const character=boot.model.rendererType==='inochi-0.8-subset'?new InochiRenderer({canvas,onStatus:status=>{$('model-status').textContent=[status.message,...status.capabilities?.warnings??[]].join('；');$<HTMLButtonElement>('test-eating').disabled=!status.capabilities?.eating;$<HTMLButtonElement>('test-typing').disabled=!status.capabilities?.typing;for(const button of document.querySelectorAll<HTMLButtonElement>('[data-mood]'))button.disabled=!status.capabilities?.moods.includes(button.dataset.mood||'');}}):new Character2D(canvas);if(character instanceof InochiRenderer)await character.load(boot.model);else await character.load();window.whale.on('model',()=>window.location.reload());new ResizeObserver(()=>character.resize(canvas.clientWidth,canvas.clientHeight)).observe(canvas);function animate(){const now=performance.now();if(now-lastFrame>=(character instanceof InochiRenderer?16:40)){const previewMeal=mealPreview.view(now);character.update({physical:physicalDemo(now-physicalPreviewStarted)??physical,timeSeconds:now/1000,deltaSeconds:Math.min(.1,(now-lastFrame)/1000),mood:settings.mood,sleeping:isWithinSleepSchedule(settings,new Date()),typing:now<previewTyping?1:0,bounce:now<previewBounce?1:0,eating:previewMeal.eating,hidingBowl:previewMeal.hidingBowl,innocent:previewMeal.innocent,audioLevel:settings.audioEnabled?audioLevel:0,reducedMotion:settings.reducedMotion,gaze:previewGaze});if(character instanceof InochiRenderer)window.__inochiQA={modelName:boot.model.name,modelUrl:boot.model.modelUrl,backend:character.backend,activeScene:character.activeScene,activeModelUrl:character.activeModelUrl,workCapabilities:character.workCapabilities,renderMilliseconds:character.renderMilliseconds,drivenParameters:character.lastParameters,capabilities:character.capabilities,preview:previewMeal};lastFrame=now;}}previewLoop.setBlocked('model-loading',false);
let previousSleeping=false;function updateClock(){const now=new Date();const sleeping=isWithinSleepSchedule(settings,now);if(sleeping&&!previousSleeping&&(audioState.state==='active'||audioState.state==='requesting')){void audio.stop();toast('进入作息睡眠，已关闭音频设备。起床后可手动再开启律动');}previousSleeping=sleeping;$('clock').textContent=now.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});$('date').textContent=now.toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'short'});$('sleep-status').textContent=settings.sleepEnabled?(isWithinSleepSchedule(settings,now)?'正在定时睡眠，关闭作息即可唤醒':'现在是清醒时段'):'作息已关闭，不会按时间强制睡觉';}setInterval(updateClock,1000);updateClock();paint();document.body.dataset.ready='true';window.addEventListener('beforeunload',()=>{void audio.destroy();character.destroy();});let lastLocalActivity=0;for(const name of ['pointerdown','pointermove','keydown'] as const)document.addEventListener(name,()=>{const now=performance.now();if(name==='pointermove'&&now-lastLocalActivity<100)return;lastLocalActivity=now;window.whale.activity({kind:name==='keydown'?'typing':name==='pointerdown'?'click':'pointer'});});
